### ISSUE TITLE
分词 

### ISSUE THREAD

**Issue by xxllp** [JunnYu/GPLinker_pytorch#2]
看数据里面都做了分词操作 这个是需要要的吗

**Comment by JunnYu** [comment]
你好，请问你说的分词操作是哪部分代码？

**Comment by xxllp** [comment]
dev  data 下面的 spo数据里面 
{"word": "《", "pos": "w"}, {"word": "深夜烘焙坊", "pos": "nw"}, {"word": "》", "pos": "w"}, {"word": "是", "pos": "v"}, {"word": "同名", "pos": "vn"}
但是搜了下代码 好像没有用到

**Comment by JunnYu** [comment]
是的，都没有使用，苏神的代码中也没使用这部分

**Comment by xxllp** [comment]
好的

**Comment by xxllp** [comment]
还有个问题想问下  我看这个dev 里面到处都是 分布式的代码 但是我想单卡跑 不想要这些库  这个改起来会不会有些麻烦
